#
# Welcome to Magento 2 Docker Configuration
#  _ __ ___   __ _  __ _  ___ _ __ __  __
# | '_ ` _ \ / _` |/ _` |/ _ \ '_ \\ \/ /
# | | | | | | (_| | (_| |  __/ | | |>  < 
# |_| |_| |_|\__,_|\__, |\___|_| |_/_/\_\
#                   __/ |                
#                  |___/                 
#
# This config was created by magenx.com
# If you have any questions or need help
# please dont hesitate to contact us at:
#
# [admin email]: admin@magenx.com
# [website url]: https://www.magenx.com
#

# # ---------------------------------------------------------------------------------------------------------------------#
#  Configure logger driver
# # ---------------------------------------------------------------------------------------------------------------------#
x-logger: &logger
        logging:
            driver: syslog
            options:
                syslog-address: "unixgram:///dev/log"
                mode: non-blocking
                tag: "[ {{.Name}} ]"
                
# # ---------------------------------------------------------------------------------------------------------------------#
#  Configure ulimits
# # ---------------------------------------------------------------------------------------------------------------------#
x-ulimits: &ulimits
        ulimits:
            memlock:
               soft: -1
               hard: -1
            nofile:
               soft: 65536
               hard: 65536

# # ---------------------------------------------------------------------------------------------------------------------#
#  Configure capabilities
# # ---------------------------------------------------------------------------------------------------------------------#
x-cap_add: &cap_add
        cap_add:
            - SYS_PTRACE

services:
# # ---------------------------------------------------------------------------------------------------------------------#
#  MariaDB is a high performing open source relational database
# # ---------------------------------------------------------------------------------------------------------------------#
    mariadb:
        image: mariadb:${MARIADB_VERSION}
        container_name: mariadb
        hostname: mariadb
        environment:
            - MARIADB_AUTO_UPGRADE
            - MARIADB_DISABLE_UPGRADE_BACKUP
            - MARIADB_RANDOM_ROOT_PASSWORD
            - MARIADB_DATABASE
            - MARIADB_USER
            - MARIADB_PASSWORD
            - TIMEZONE
        command: >
            --key_buffer_size=16M
            --myisam-recover-options=FORCE,BACKUP
            --innodb=force
            --max_allowed_packet=250M
            --max_connect_errors=100000
            --bind-address=mariadb
            --skip-name-resolve
            --back_log=20
            --interactive_timeout=7200
            --wait_timeout=7200
            --net_read_timeout=120
            --net_write_timeout=300
            --sort_buffer_size=1M
            --read_buffer_size=1M
            --read_rnd_buffer_size=1M
            --join_buffer_size=1M
            --tmp_table_size=128M
            --max_heap_table_size=128M
            --max_connections=150
            --thread_cache_size=32
            --thread_pool_size=16
            --open_files_limit=65535
            --table_definition_cache=4000
            --table_open_cache=4000
            --innodb_lock_wait_timeout=7200
            --innodb_flush_log_at_trx_commit=2
            --innodb_log_file_size=128M
            --innodb_log_buffer_size=8M
            --innodb_read_io_threads=8
            --innodb_write_io_threads=8
            --innodb_buffer_pool_size=2G
            --skip-log-bin
            --disable-log-bin
        ports:
            - "127.0.0.1:3306:3306"
        volumes:
            - ${DATA}/mariadb:/var/lib/mysql
        restart: always
        cpu_shares: 1024
        mem_limit: 2048m
        mem_reservation: 512m
        oom_kill_disable: true
        healthcheck:
            test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized", "--innodb_buffer_pool_loaded"]
            start_period: 10s
            interval: 10s
            timeout: 5s
            retries: 3
        << : [*ulimits, *logger]


# # ---------------------------------------------------------------------------------------------------------------------#
#  Opensearch is a powerful open source search and analytics engine
# # ---------------------------------------------------------------------------------------------------------------------#
    opensearch:
        container_name: opensearch
        hostname: opensearch
        build:
            context: ./opensearch
            args:
              OPENSEARCH_VERSION:
        environment:
            - cluster.name=${BRAND}-cluster
            - node.name=${BRAND}-node1
            - node.attr.rack=${BRAND}-rack1
            - discovery.type=single-node
            - cluster.routing.allocation.enable=all
            - bootstrap.memory_lock=true
            - plugins.security.ssl.transport.enforce_hostname_verification=false
            - plugins.security.ssl.http.enabled=false
            - plugins.security.allow_unsafe_democertificates=true
            - plugins.security.allow_default_init_securityindex=true
            - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
            - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_PASSWORD}
        ports:
            - "127.0.0.1:9200:9200"
            - "127.0.0.1:9300:9300"
        volumes:
            - ${DATA}/opensearch:/usr/share/opensearch/data
            - ${DATA}/opensearch/logs:/usr/share/opensearch/logs
        restart: always
        cpu_shares: 1024
        mem_limit: 2048m
        mem_reservation: 512m
        oom_kill_disable: true
        healthcheck:
            test: ["CMD-SHELL", "curl -XGET -u admin:${OPENSEARCH_PASSWORD} 'http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=15s' || exit 1"]
            start_period: 15s
            interval: 15s
            timeout: 5s
            retries: 3
        << : [*ulimits, *logger]


# # ---------------------------------------------------------------------------------------------------------------------#
#  Redis is an open source key-value store that functions as a data structure server.
# # ---------------------------------------------------------------------------------------------------------------------#
    cache:
        image: &redis_image redis:${REDIS_VERSION}-alpine
        container_name: cache
        hostname: cache
        command: >
            --bind cache
            --port 6380
            --save ""
            --loglevel warning
            --requirepass ${REDIS_PASSWORD}
            --maxmemory ${REDIS_CACHE_MEMORY}
            --maxmemory-policy allkeys-lru
            --lazyfree-lazy-eviction yes
            --lazyfree-lazy-expire yes
            --lazyfree-lazy-server-del yes
            --replica-lazy-flush yes
            --lazyfree-lazy-user-del yes
        ports:
            - "127.0.0.1:6380:6380"
        restart: always
        cpu_shares: 614
        mem_limit: 1024mb
        mem_reservation: 128m
        oom_kill_disable: true
        << : [*ulimits, *logger]


# # ---------------------------------------------------------------------------------------------------------------------#
#  Redis is an open source key-value store that functions as a data structure server.
# # ---------------------------------------------------------------------------------------------------------------------#
    session:
        image: *redis_image
        container_name: session
        hostname: session
        command: >
            --bind session
            --port 6379
            --save 300 15
            --requirepass ${REDIS_PASSWORD}
            --maxmemory ${REDIS_SESSION_MEMORY}
            --maxmemory-policy allkeys-lru
            --lazyfree-lazy-eviction yes
            --lazyfree-lazy-expire yes
            --lazyfree-lazy-server-del yes
            --replica-lazy-flush yes
            --lazyfree-lazy-user-del yes
        ports:
            - "127.0.0.1:6379:6379"
        volumes:
            - ${DATA}/redis:/data
        restart: always
        cpu_shares: 614
        mem_limit: 1024mb
        mem_reservation: 128m
        oom_kill_disable: true
        << : [*ulimits, *logger]


# # ---------------------------------------------------------------------------------------------------------------------#
#  RabbitMQ is an open source multi-protocol messaging broker
# # ---------------------------------------------------------------------------------------------------------------------#                
    rabbitmq:
        image: rabbitmq:${RABBITMQ_VERSION}-alpine
        container_name: rabbitmq
        hostname: rabbitmq
        environment:
            - RABBITMQ_DEFAULT_USER=${BRAND}
            - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
        ports:
            - "127.0.0.1:5672:5672"
        volumes:
            - ${DATA}/rabbitmq:/var/lib/rabbitmq
        restart: always
        cpu_shares: 614
        mem_limit: 512m
        mem_reservation: 128m
        oom_kill_disable: true
        << : [*ulimits, *logger]
                
                
# # ---------------------------------------------------------------------------------------------------------------------#
#  Varnish is an HTTP accelerator designed for content-heavy dynamic web sites as well as APIs.
# # ---------------------------------------------------------------------------------------------------------------------#                  
    varnish:
        container_name: varnish
        hostname: varnish
        build:
            context: ./varnish
            args:
              VARNISH_VERSION:
              VARNISH_CACHE_SIZE:
              TIMEZONE:
        depends_on:
            - nginx
            - php
        ports:
            - "127.0.0.1:8081:8081"
            - "127.0.0.1:6082:6082" 
        user: varnish
        restart: always
        cpu_shares: 614
        mem_limit: 1024m
        mem_reservation: 128m
        << : [*ulimits, *logger]


# # ---------------------------------------------------------------------------------------------------------------------#
#  Configure container to run php and php-fpm
# # ---------------------------------------------------------------------------------------------------------------------#    
    php:
        container_name: php
        hostname: php
        build:
            context: ./php
            args: &magento_env
              BRAND:
              DOMAIN:
              PHP_USER:
              ADMIN_PATH:
              ROOT_PATH:
              PHP_PACKAGES:
              PHP_VERSION:
              PHP_FPM_POOL:
              PHP_INI:
              TIMEZONE:
              ALPINE_VERSION:
        environment: &php_env
            - MARIADB_DATABASE
            - MARIADB_USER
            - MARIADB_PASSWORD
            - RABBITMQ_PASSWORD
            - REDIS_PASSWORD
            - INDEXER_PASSWORD
            - BRAND
            - DOMAIN
            - ROOT_PATH
            - ADMIN_PATH
            - CRYPT_KEY
        depends_on:
            mariadb:
                condition: service_healthy
        ports:
            - "127.0.0.1:9000:9000"
        volumes:
            - ${MAGENTO}/${BRAND}/current:${ROOT_PATH}/public:ro
            - ${MAGENTO}/${BRAND}/shared/var:${ROOT_PATH}/public/var
            - ${MAGENTO}/${BRAND}/shared/pub/media:${ROOT_PATH}/public/pub/media
        working_dir: "${ROOT_PATH}/public"
        user: ${PHP_USER}
        entrypoint: ["php-fpm${PHP_VERSION}", "-F"]
        restart: always
        cpu_shares: 1024
        mem_limit: 2048m
        mem_reservation: 512m
        << : [*ulimits, *cap_add, *logger]



# # ---------------------------------------------------------------------------------------------------------------------#
#  Configure container for magento app
# # ---------------------------------------------------------------------------------------------------------------------#    
    magento:
        container_name: magento
        build:
            context: ./magento
            args: *magento_env
            additional_contexts:
              php: "service:php"
        environment: *php_env
        volumes:
            - ${MAGENTO}/${BRAND}/current:${ROOT_PATH}/public:ro
            - ${MAGENTO}/${BRAND}/shared/var:${ROOT_PATH}/public/var
            - ${MAGENTO}/${BRAND}/shared//pub/media:${ROOT_PATH}/public/pub/media
        working_dir: "${ROOT_PATH}/public"
        user: ${BRAND}
        entrypoint: ["/entrypoint.sh"]
        cpu_shares: 614
        mem_limit: 1024m
        mem_reservation: 128m
        << : [*ulimits, *logger]


# # ---------------------------------------------------------------------------------------------------------------------#
#  Nginx is an open source reverse proxy server for HTTP, HTTPS
# # ---------------------------------------------------------------------------------------------------------------------#                   
    nginx:
        build:
            context: ./nginx
            args: *magento_env
        container_name: nginx
        hostname: nginx
        restart: always
        depends_on:
            mariadb:
                condition: service_healthy
            php:
                condition: service_started
        ports:
            - "80:80"
            - "443:443"
            - "127.0.0.1:8080:8080"
        volumes:
            - ${MAGENTO}/${BRAND}/current:${ROOT_PATH}/public:ro
            - ${MAGENTO}/${BRAND}/shared/var:${ROOT_PATH}/public/var:ro
            - ${MAGENTO}/${BRAND}/shared/pub/media:${ROOT_PATH}/public/pub/media:ro
            - ${DATA}/ssl:/etc/ssl
            - ${DATA}/letsencrypt:/etc/letsencrypt:ro
            - ${DATA}/phpmyadmin:/var/www/html:ro
        working_dir: "${ROOT_PATH}/public"
        user: ${BRAND}
        cpu_shares: 614
        mem_limit: 512m
        mem_reservation: 128m
        << : [*ulimits, *logger]


# # ---------------------------------------------------------------------------------------------------------------------#
#   Composer is a dependency manager written in and for PHP
# # ---------------------------------------------------------------------------------------------------------------------# 
    composer:
        build:
            context: ./composer
            args:
              <<: *magento_env
            additional_contexts:
              php: "service:php"
        container_name: composer
        environment:
            COMPOSER_AUTH: |
              {
                "http-basic": {
                  "repo.magento.com": {
                    "username": "${COMPOSER_USER}",
                    "password": "${COMPOSER_PASSWORD}"
                  }
                }
              }
        volumes:
            - ${MAGENTO}/${BRAND}/current:${ROOT_PATH}/public
            - ${MAGENTO}/${BRAND}/shared/var:${ROOT_PATH}/public/var
            - ${MAGENTO}/${BRAND}/shared/pub/media:${ROOT_PATH}/public/pub/media
        working_dir: "${ROOT_PATH}/public"
        user: ${BRAND}
        entrypoint: ["composer"]
        cpu_shares: 1024
        mem_limit: 1024m
        mem_reservation: 512m
        << : [*ulimits, *logger]


# # ---------------------------------------------------------------------------------------------------------------------#
#  phpMyAdmin - A web interface for MariaDB
# # ---------------------------------------------------------------------------------------------------------------------#  
    phpmyadmin:
        image: phpmyadmin:fpm-alpine
        container_name: phpmyadmin
        hostname: phpmyadmin
        environment:
            - PMA_ARBITRARY
            - HIDE_PHP_VERSION
            - PMA_HOST
            - PMA_PORT
            - MAX_EXECUTION_TIME
            - MEMORY_LIMIT
            - UPLOAD_LIMIT
            - PMA_PMADB
            - PMA_CONTROLUSER
            - PMA_CONTROLPASS
            - TIMEZONE
        restart: always
        depends_on:
            mariadb:
                condition: service_healthy
            nginx:
                condition: service_started
        ports:
            - "127.0.0.1:9001:9001"
        volumes:
            - ${DATA}/phpmyadmin:/var/www/html
        cpu_shares: 614
        mem_limit: 512m
        mem_reservation: 512m
        << : [*ulimits, *logger]


# # ---------------------------------------------------------------------------------------------------------------------#
#   Certbot tool for obtaining TLS/SSL certificates from Let's Encrypt
# # ---------------------------------------------------------------------------------------------------------------------#           
    certbot:
        image: certbot/certbot:latest
        container_name: certbot
        volumes:
            - ${MAGENTO}/${BRAND}/current:${ROOT_PATH}/public/pub/.well-known/acme-challenge/:rw
            - ${DATA}/letsencrypt:/etc/letsencrypt
            - ${DATA}/letsencrypt:/var/lib/letsencrypt
        << : [*ulimits, *logger]


# # ---------------------------------------------------------------------------------------------------------------------#
#   Cron job scheduler run arbitrary commands, or "jobs", according to a schedule
# # ---------------------------------------------------------------------------------------------------------------------# 
    cron:
        build:
            context: ./cron
            args: *magento_env
            additional_contexts:
              php: "service:php"
        container_name: cron
        environment: *php_env
        depends_on:
            mariadb:
                condition: service_healthy
        volumes:
            - ${MAGENTO}/${BRAND}/current:${ROOT_PATH}/public
            - ${MAGENTO}/${BRAND}/shared/var:${ROOT_PATH}/public/var
            - ${MAGENTO}/${BRAND}/shared/pub/media:${ROOT_PATH}/public/pub/media
        working_dir: "${ROOT_PATH}/public"
        user: ${PHP_USER}
        command: ["crond", "-f"]
        cpu_shares: 1024
        mem_limit: 2048m
        mem_reservation: 512m
        << : [*ulimits, *logger]


# # ---------------------------------------------------------------------------------------------------------------------#
#   Named networks list
# # ---------------------------------------------------------------------------------------------------------------------# 
networks:
    default:
        name: ${BRAND}
